name: graphdti
channels:
  - bioconda
  - pytorch
  - pyg
  - nvidia
  - conda-forge
dependencies:
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pyg=2.5.0
  - pyg-lib=0.4.0
  - snakefmt=0.10.0
  - snakemake-minimal=7.32.4
  - pandas=2.2.1
  - pyarrow=14.0.2
  - tensorboard=2.16.2
  - seaborn=0.13.2
  - awscli=2.16.5
  - pip=24.0
  - pip:
    - torcheval
